# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod ‘AFNetworking’
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'FMDB'
pod 'Masonry'

target '小熊早知道' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 小熊早知道

  target '小熊早知道Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '小熊早知道UITests' do
    inherit! :search_paths
    # Pods for testing

  end

end
